<!DOCTYPE html>
<html>
<head>
    <title>Exam Timetable</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

        body {
            font-family: 'Inter', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f9fafb;
            color: #333;
        }

        h1 {
            text-align: center;
            color: #1d4ed8;
            font-size: 24px;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            background-color: #ffffff;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        th {
            background-color: #1d4ed8;
            color: #ffffff;
            text-align: left;
            padding: 12px;
            font-weight: 600;
            font-size: 14px;
        }

        td {
            padding: 12px;
            font-size: 14px;
            color: #555;
            border-bottom: 1px solid #e5e7eb;
        }

        tr:last-child td {
            border-bottom: none;
        }

        tr:nth-child(even) {
            background-color: #f3f4f6;
        }

        .footer {
            text-align: center;
            margin-top: 20px;
            font-size: 12px;
            color: #6b7280;
        }
    </style>
</head>
<body>
    <h1>Exam Timetable</h1>
    <table>
        <thead>
            <tr>
                <th>Day</th>
                <th>Date</th>
                <th>Unit</th>
                <th>Time</th>
                <th>Venue</th>
                <th>Chief Invigilator</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($timetables as $timetable)
                <tr>
                    <td>{{ $timetable->day }}</td>
                    <td>{{ $timetable->date }}</td>
                    <td>{{ $timetable->unit_name }}</td>
                    <td>{{ $timetable->start_time }} - {{ $timetable->end_time }}</td>
                    <td>{{ $timetable->venue }}</td>
                    <td>{{ $timetable->chief_invigilator }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div class="footer">
        Generated by MyClassTimetable &copy; {{ date('Y') }}
    </div>
</body>
</html>
