<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClassTimeSlotSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('class_time_slots')->insert([
            
            // Monday Online
            [
                'day' => 'Monday',
                'start_time' => '08:15:00',
                'end_time' => '09:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Monday',
                'start_time' => '09:15:00',
                'end_time' => '10:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Monday',
                'start_time' => '10:15:00',
                'end_time' => '11:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Monday',
                'start_time' => '11:15:00',
                'end_time' => '12:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Monday',
                'start_time' => '12:15:00',
                'end_time' => '13:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Monday',
                'start_time' => '13:15:00',
                'end_time' => '14:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Monday',
                'start_time' => '14:15:00',
                'end_time' => '15:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Monday',
                'start_time' => '15:15:00',
                'end_time' => '16:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Monday',
                'start_time' => '16:15:00',
                'end_time' => '17:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tuesday Online
            [
                'day' => 'Tuesday',
                'start_time' => '08:15:00',
                'end_time' => '09:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Tuesday',
                'start_time' => '09:15:00',
                'end_time' => '10:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Tuesday',
                'start_time' => '10:15:00',
                'end_time' => '11:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Tuesday',
                'start_time' => '11:15:00',
                'end_time' => '12:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Tuesday',
                'start_time' => '12:15:00',
                'end_time' => '13:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Tuesday',
                'start_time' => '13:15:00',
                'end_time' => '14:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Tuesday',
                'start_time' => '14:15:00',
                'end_time' => '15:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Tuesday',
                'start_time' => '15:15:00',
                'end_time' => '16:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Tuesday',
                'start_time' => '16:15:00',
                'end_time' => '17:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Wednesday Online
            [
                'day' => 'Wednesday',
                'start_time' => '08:15:00',
                'end_time' => '09:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Wednesday',
                'start_time' => '09:15:00',
                'end_time' => '10:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Wednesday',
                'start_time' => '10:15:00',
                'end_time' => '11:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Wednesday',
                'start_time' => '11:15:00',
                'end_time' => '12:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Wednesday',
                'start_time' => '12:15:00',
                'end_time' => '13:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Wednesday',
                'start_time' => '13:15:00',
                'end_time' => '14:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Wednesday',
                'start_time' => '14:15:00',
                'end_time' => '15:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Wednesday',
                'start_time' => '15:15:00',
                'end_time' => '16:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Wednesday',
                'start_time' => '16:15:00',
                'end_time' => '17:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Thursday Online
            [
                'day' => 'Thursday',
                'start_time' => '08:15:00',
                'end_time' => '09:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Thursday',
                'start_time' => '09:15:00',
                'end_time' => '10:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Thursday',
                'start_time' => '10:15:00',
                'end_time' => '11:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Thursday',
                'start_time' => '11:15:00',
                'end_time' => '12:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Thursday',
                'start_time' => '12:15:00',
                'end_time' => '13:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Thursday',
                'start_time' => '13:15:00',
                'end_time' => '14:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Thursday',
                'start_time' => '14:15:00',
                'end_time' => '15:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Thursday',
                'start_time' => '15:15:00',
                'end_time' => '16:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Thursday',
                'start_time' => '16:15:00',
                'end_time' => '17:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Friday Online
            [
                'day' => 'Friday',
                'start_time' => '08:15:00',
                'end_time' => '09:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Friday',
                'start_time' => '09:15:00',
                'end_time' => '10:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Friday',
                'start_time' => '10:15:00',
                'end_time' => '11:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Friday',
                'start_time' => '11:15:00',
                'end_time' => '12:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Friday',
                'start_time' => '12:15:00',
                'end_time' => '13:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Friday',
                'start_time' => '13:15:00',
                'end_time' => '14:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Friday',
                'start_time' => '14:15:00',
                'end_time' => '15:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Friday',
                'start_time' => '15:15:00',
                'end_time' => '16:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Friday',
                'start_time' => '16:15:00',
                'end_time' => '17:15:00',
                'status' => 'Online',
                'created_at' => now(),
                'updated_at' => now(),
            ],    
            // Physical 
            [
                'day' => 'Monday',
                'start_time' => '08:15:00',
                'end_time' => '10:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],    
            [
                'day' => 'Monday',
                'start_time' => '10:15:00',
                'end_time' => '12:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Monday',
                'start_time' => '12:15:00',
                'end_time' => '14:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Monday',
                'start_time' => '14:15:00',
                'end_time' => '16:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tuesday Physical
          
            [
                'day' => 'Tuesday',
                'start_time' => '08:15:00',
                'end_time' => '10:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Tuesday',
                'start_time' => '10:15:00',
                'end_time' => '12:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Tuesday',
                'start_time' => '12:15:00',
                'end_time' => '14:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Tuesday',
                'start_time' => '14:15:00',
                'end_time' => '16:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Wednesday Physical
            [
                'day' => 'Wednesday',
                'start_time' => '08:15:00',
                'end_time' => '10:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Wednesday',
                'start_time' => '10:15:00',
                'end_time' => '12:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Wednesday',
                'start_time' => '12:15:00',
                'end_time' => '14:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Wednesday',
                'start_time' => '14:15:00',
                'end_time' => '16:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Thursday Physical
            [
                'day' => 'Thursday',
                'start_time' => '08:15:00',
                'end_time' => '10:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Thursday',
                'start_time' => '10:15:00',
                'end_time' => '12:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Thursday',
                'start_time' => '12:15:00',
                'end_time' => '14:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Thursday',
                'start_time' => '14:15:00',
                'end_time' => '16:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ], 
            // Friday Physical
            [
                'day' => 'Friday',
                'start_time' => '08:15:00',
                'end_time' => '10:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Friday',
                'start_time' => '10:15:00',
                'end_time' => '12:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Friday',
                'start_time' => '12:15:00',
                'end_time' => '14:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'day' => 'Friday',
                'start_time' => '14:15:00',
                'end_time' => '16:15:00',
                'status' => 'Physical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
              
            
        ]);
    }
}
